Issue tebu 7
RyanQueirozS/Tebu pull request #13
Opened 2023-12-31 01:38 UTC by leo5123

2023-12-31 14:18 UTC, RyanQueirozS commented on internal/game/components/craft/craft.go
> +func buyTorch(i *discordgo.InteractionCreate, lastSave *models.PlayerSave) {
craftTorch. Depois vamos em call, tive uma ideia sobre o mapa de Itens

2023-12-31 14:18 UTC, RyanQueirozS commented on internal/game/components/craft/craft.go
> +func canBuy(lastSave *models.PlayerSave) {
canCraft

2023-12-31 14:22 UTC, RyanQueirozS requested changes
Muito bom!

2023-12-31 14:22 UTC, RyanQueirozS commented on internal/game/quests/Quest0.go
> +			Content: "Game started!\n *Remember: read the prompt and the button text*",
Talvez fique melhor em **Negrito**

2023-12-31 14:22 UTC, RyanQueirozS commented on internal/game/components/craft/craft.go
> +func buyTorch(i *discordgo.InteractionCreate, lastSave *models.PlayerSave) {
craftTorch. Depois vamos em call, tive uma ideia sobre o mapa de Itens

2023-12-31 14:40 UTC, leo5123 commented on internal/game/quests/Quest0.go
> +			Content: "Game started!\n *Remember: read the prompt and the button text*",
homofóbico

2023-12-31 16:06 UTC, RyanQueirozS requested changes

2023-12-31 16:06 UTC, RyanQueirozS commented on internal/game/components/craft/craft.go
> +func buyTorch(i *discordgo.InteractionCreate, lastSave *models.PlayerSave) {
craftTorch

2024-01-01 23:28 UTC, RyanQueirozS approved these changes

2024-01-01 23:28 UTC, merged